
services:
  web:
    build:
      context: ./web  # Carpeta que contiene el Dockerfile de la aplicación web
    expose:
      - "8000"  # Exponer el puerto interno para que Nginx pueda acceder a él
    environment:
      DATABASE_URL: mysql://user:userpassword@db/mydatabase

  nginx:
    build:
      context: ./nginx  # Carpeta que contiene el Dockerfile de Nginx
    ports:
      - "80:80"  # Mapea el puerto 80 del host al contenedor
    depends_on:
      - web  # Asegura que el servicio web esté corriendo antes de Nginx

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: