
services:
  kukulc4n-web-cont-dev:
    image: ogtdocker/kukulc4n-img-web-dev:v.1.2 
    ports:
      - "4321:80"  
    environment:
      - DATABASE_URL=sqlite:///test-kuku.db
    depends_on:
      - db
  db:
    image:  api-prv:v.1.2
    environment:
      - SQLITE_FILE=test-kuku.db
    ports:
      - "8000:8000"

